### ISSUE TITLE
Installation via git clone creates $HOME/~ folder

### ISSUE THREAD

**Issue by scruss** [10sr/editorconfig-micro#12]
When I installed via

    git clone https://github.com/10sr/editorconfig-micro "${XDG_CONFIG_HOME:-~/.config}/micro/plug/editorconfig"

git inconveniently created a folder called `~` in $HOME:

    $ find \~
    ~
    ~/.config
    ~/.config/micro
    ~/.config/micro/plug
    ~/.config/micro/plug/editorconfig

**Comment by joshuarli** [comment]
Hmm, your shell should have expanded `~/.config`. What shell are you running? I should probably replace that with $HOME though. Can you try:

    git clone https://github.com/10sr/editorconfig-micro "${XDG_CONFIG_HOME:-${HOME}/.config}/micro/plug/editorconfig"

**Comment by joshuarli** [comment]
Closing under the assumption that you've solved the issue on your end, feel free to reopen.
