### ISSUE TITLE
Error while parsing .editorconfig on Windows 

### ISSUE THREAD

**Issue by tomstein** [10sr/editorconfig-micro#14]
Here we should add a '\r' to gmatch expression:
https://github.com/10sr/editorconfig-micro/blob/dfb1c41733206275f4f2cfbcc6a105112d1d2058/editorconfig.lua#L114
Reason: On Windows editorconfig executable returns content of .editorconfig with trailing CRLF (\r\n) instead of unix style LF (\n).
I fixed this locally and it works as expected.

**Comment by 10sr** [comment]
I think this should be fixed with #15.
