### ISSUE TITLE
Modification prompt is appearing even without file modification

### ISSUE THREAD

**Issue by joshuarli** [10sr/editorconfig-micro#4]
Hmm, just noticed an interesting bug with 0.2.0 - files that are opened then closed without modification will not close immediately due to the "save changes before closing" prompt, which shouldn't appear.

**Comment by joshuarli** [comment]
Ok, this is solely being caused by `setEndOfLine` in the plugin, but I'm not entirely sure why yet. I hate line ending issues >.>

**Comment by joshuarli** [comment]
@10sr can you confirm this behavior on your side? I hadn't noticed this during development because I was editing files all the time. If it doesn't happen on your side, it's likely I have some other editor or git configuration that's messing with the line endings.

**Comment by 10sr** [comment]
Oh I'm experiencing the same issue...
(I'm going to bed now so I'll look into it tomorrow!)

**Comment by 10sr** [comment]
I think we can check the value first and call `SetLocalOption` only when the value has been changed.

https://github.com/10sr/editorconfig-micro/blob/master/editorconfig.lua#L18

I'll do it later, or willing to review if you can fix it!
