### ISSUE TITLE
Log is very noisy

### ISSUE THREAD

**Issue by sum01** [10sr/editorconfig-micro#6]
Every save of a file is triggering 11 lines to be written to the log, each and every save. It's fine to print anytime a setting changes, but it prints even when there's no changes, which is quite spammy.

Plugin version `0.2.1`, Micro version `1.4.1-dev.23`

**Comment by 10sr** [comment]
Thanks for your feedback!
Released v0.2.2, which stop writing some logs by default.

**Comment by sum01** [comment]
Indeed it's much quieter, but it still logs `EditorConfig <filenamehere>: Set tabstospaces = off` on every save, even though it already said it on file load.

**Comment by joshuarli** [comment]
@sum01 This should be fixed with #7! Thanks for letting us know.
