### ISSUE TITLE
Value utf-8 for editorconfig property charset is not currently supported by micro.

### ISSUE THREAD

**Issue by indrakaw** [10sr/editorconfig-micro#9]
I got a prompt:
```
EditorConfig <FileName>: Value utf-8 for editorconfig property charset is not currently supported by micro.
```
What with this? I need an explanation and this is annoying.

OS: Windows 10
Both of `micro` and `editorconfig` are installed via Scoop.sh

**Comment by joshuarli** [comment]
That [shouldn't](https://github.com/10sr/editorconfig-micro/blob/master/editorconfig.lua#L68) be happening, because the logic is either `utf-8` is set in the effective/calculated editorconfig, or it isn't present.

The only reason I can think of is you have unicode homoglyphs in your editorconfig, and something cleaned them before it was posted in your comment here. Try typing utf-8 by hand in your editorconfig?

**Comment by indrakaw** [comment]
I don't really get it but it wasn't on directory with `.editorconfig`. I was randomly open file from Downloads folder.

Is there global path for editorconfig?

**Comment by joshuarli** [comment]
There isn't a hardcoded path to a global configuration file for EditorConfig. From the [website](https://editorconfig.org/):

> When opening a file, EditorConfig plugins look for a file named .editorconfig in the directory of the opened file and in every parent directory. A search for .editorconfig files will stop if the root filepath is reached or an EditorConfig file with root=true is found.

It follows that what most people tend to do is put a big file with sane, generic defaults in `~/.editorconfig`.

**Comment by indrakaw** [comment]
Oh. I found one on`%user_profle%`. I renamed it into something else, and no prompt. It runs normally.

I have no idea what's wrong. So here, please review my `.editorconfig` file (see attachment).
[.editorconfig.txt](https://github.com/10sr/editorconfig-micro/files/3101076/default.editorconfig.txt)

**Comment by joshuarli** [comment]
It looks fine to me. I also tested it, and can't reproduce your error.

**Comment by indrakaw** [comment]
Yes. It's odds. My assumption is it has something to do with the text encoding on `.editorconfig.txt` itself. Remote version must had encoded.

![image](https://user-images.githubusercontent.com/9590878/56491246-1e14b100-6512-11e9-8959-f2434dac8938.png)

Edit:
Here's editorconfig of mine -
```
λ editorconfig.exe --version
EditorConfig C Core Version 0.12.1
```
